# Values for the Python application
python:
  replicaCount: 2
  image:
    repository: tanish0510/demo-app
    tag: v20250822130835
  service:
    type: NodePort
    port: 5000
    targetPort: 5000
    nodePort: 30008
# Values for the Redis database
redis:
  replicaCount: 1
  image:
    repository: redis
    tag: latest
  service:
    port: 6379
    targetPort: 6379
