# demo-app-chart/templates/redis-deployment-and-service.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "demo-app-chart.fullname" . }}-redis
spec:
  replicas: {{ .Values.redis.replicaCount }}
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image.repository }}:{{ .Values.redis.image.tag }}"
        ports:
        - containerPort: 6379
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "demo-app-chart.fullname" . }}-redis-service
spec:
  type: ClusterIP
  selector:
    app: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379