name: Test and Build

on:
  push:
    branches:
      - main
    paths:
      - '**/*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Setting up environment
      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Checkout Helm Chart repository
        uses: actions/checkout@v2
        with:
          repository: tanish0510/argo-cd-demo 
          path: .
          
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      - name: Docker Setup
        uses: docker/setup-buildx-action@v2

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8
          
      - name: Run Linting tests
        run: |
          flake8 --ignore=E501,F401 .
      
      - name: Docker Credentials
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Docker tag
        id: version
        run: |
          VERSION=v$(date +"%Y%m%d%H%M%S")
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Build Docker Image
        run: |
          docker build . -t tanish0510/demo-app:${{ env.VERSION }} 
    
      - name: Push Docker Image
        run: |
          docker push tanish0510/demo-app:${{ env.VERSION }}
      
    # This is the critical change for the GitOps workflow
      - name: Update Helm Chart values
        run: |
          # Use 'sed' to replace the 'tag' in your values.yaml file
          sed -i "s|tag: .*|tag: ${{ env.VERSION }}|g" demo-app-chart/values.yaml
          cat demo-app-chart/values.yaml
          
      - name: Commit the changes
        run: |
          git config --global user.email "<>"
          git config --global user.name "GitHub Actions Bot"
          git add demo-app-chart/values.yaml
          git commit -m "Update Helm chart with new image version - ${{ env.VERSION }}"
          git remote set-url origin https://github-actions:${{ secrets.GITHUB_TOKEN }}@github.com/tanish0510/argo-cd-demo.git
          git push origin main